[package]
name = "coco-bot"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15"
poise = { git = "https://github.com/serenity-rs/poise.git", branch = "serenity-next" }
serenity = { git = "https://github.com/serenity-rs/serenity.git", branch = "next" }
tokio = { version = "1.45.0", features = ["macros", "rt-multi-thread"] }
