from_latest_tag = false
ignore_merge_commits = false
ignore_fixup_commits = true
disable_changelog = false
disable_bump_commit = false
generate_mono_repository_global_tag = true
generate_mono_repository_package_tags = true
skip_ci = "[skip ci]"
skip_untracked = false
pre_bump_hooks = [
    "cargo build --release",
    "echo 'bumping from {{latest|0.0.0}} to {{version|0.0.1}}'",
    "cargo set-version {{version|0.0.1}}",
    "cargo check --release",
    "git add :/Cargo.lock",
]

tag_prefix = "v"

[git_hooks.commit-msg]
script = """
#!/bin/sh
set -e
cog verify --file $1
cog check
cargo fmt -v --all --check
cargo clippy
"""


[git_hooks.pre-push]
script = """
#!/bin/sh
set -e
cog check
"""


[changelog]
path = "CHANGELOG.md"
remote = "https://github.com/MRDGH2821/Coco-Bot"
owner = "MRDGH2821"
repository = "Coco-Bot"
